# Generated by Django 4.2.13 on 2024-07-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubclubgo', '0033_alter_club_email_alter_club_website_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='website_link',
            field=models.URLField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='club',
            name='website_type',
            field=models.CharField(choices=[('NA', 'None'), ('IN', 'Instagram'), ('SP', 'Student Portal'), ('HH', 'Hart House')], default='NA', max_length=2),
        ),
    ]
