# Generated by Django 4.2.13 on 2024-08-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubclubgo', '0034_alter_club_website_link_alter_club_website_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='club',
            name='website_link',
            field=models.URLField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='club',
            name='website_type',
            field=models.CharField(choices=[('HH', 'Hart House'), ('SP', 'Student Portal'), ('IN', 'Instagram'), ('NA', 'None')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
