# Generated by Django 4.2.13 on 2024-08-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubclubgo', '0035_alter_club_description_alter_club_website_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='website_type',
            field=models.CharField(choices=[('SP', 'Student Portal'), ('HH', 'Hart House'), ('IN', 'Instagram'), ('NA', 'None')], default='NA', max_length=2),
        ),
    ]
