# Generated by Django 4.2.13 on 2024-08-06 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubclubgo', '0037_club_last_updated_alter_club_website_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='club',
            name='website_type',
            field=models.CharField(choices=[('NA', 'None'), ('HH', 'Hart House'), ('SP', 'Student Portal'), ('IN', 'Instagram')], default='NA', max_length=2),
        ),
    ]
