# Generated by Django 4.2.13 on 2024-08-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubclubgo', '0038_event_date_created_alter_club_website_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='website_type',
            field=models.CharField(choices=[('NA', 'None'), ('SP', 'Student Portal'), ('IN', 'Instagram'), ('HH', 'Hart House')], default='NA', max_length=2),
        ),
    ]
