# Generated by Django 4.2.13 on 2024-08-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubclubgo', '0040_alter_club_website_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='club',
            name='website_type',
            field=models.CharField(choices=[('NA', 'None'), ('HH', 'Hart House'), ('IN', 'Instagram'), ('SP', 'Student Portal')], default='NA', max_length=2),
        ),
    ]
