# Generated by Django 4.2.13 on 2024-08-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubclubgo', '0043_alter_club_website_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='website_type',
            field=models.CharField(choices=[('HH', 'Hart House'), ('NA', 'None'), ('SP', 'Student Portal'), ('IN', 'Instagram')], default='NA', max_length=2),
        ),
    ]
