# Generated by Django 4.2.13 on 2024-08-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubclubgo', '0045_alter_club_website_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='website_type',
            field=models.CharField(choices=[('SP', 'Student Portal'), ('IN', 'Instagram'), ('HH', 'Hart House'), ('NA', 'None')], default='NA', max_length=2),
        ),
    ]
