# Generated by Django 4.2.13 on 2024-06-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubclubgo', '0002_rename_date_time_event_start_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='website_type',
            field=models.CharField(choices=[('NA', 'None'), ('IN', 'Instagram'), ('HH', 'Hart House')], default='NA', max_length=2),
        ),
    ]
